# Generated by Django 5.2 on 2026-03-29 15:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("job_created", "Job Created"),
                            ("job_completed", "Job Completed"),
                            ("job_failed", "Job Failed"),
                            ("result_accessed", "Result Accessed"),
                            ("result_deleted", "Result Deleted"),
                            ("storage_config_created", "Storage Config Created"),
                            ("storage_config_updated", "Storage Config Updated"),
                            ("storage_config_deleted", "Storage Config Deleted"),
                            ("storage_config_tested", "Storage Config Tested"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Username or client-id of the actor",
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short machine-readable detail (no content data)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("transcribe", "Transcribe"),
                            ("diarize", "Diarize"),
                            ("process", "Process"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("whisper_model", models.CharField(default="small", max_length=50)),
                ("enable_diarize", models.BooleanField(default=True)),
                ("result_text", models.TextField(blank=True, default="")),
                ("result_diarized_text", models.TextField(blank=True, default="")),
                ("result_structured_text", models.TextField(blank=True, default="")),
                ("result_summary", models.TextField(blank=True, default="")),
                ("result_segments_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this backend", max_length=200
                    ),
                ),
                (
                    "backend_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Filesystem"),
                            ("s3", "S3-compatible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default storage for new jobs"
                    ),
                ),
                (
                    "base_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Base path / prefix for stored files",
                        max_length=1024,
                    ),
                ),
                ("s3_endpoint_url", models.URLField(blank=True, default="")),
                ("s3_bucket", models.CharField(blank=True, default="", max_length=255)),
                (
                    "s3_access_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "s3_secret_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("s3_region", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
