# Generated by Django 5.2 on 2026-03-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("job_created", "Job Created"),
                    ("job_completed", "Job Completed"),
                    ("job_failed", "Job Failed"),
                    ("result_accessed", "Result Accessed"),
                    ("result_deleted", "Result Deleted"),
                    ("storage_config_created", "Storage Config Created"),
                    ("storage_config_updated", "Storage Config Updated"),
                    ("storage_config_deleted", "Storage Config Deleted"),
                    ("storage_config_tested", "Storage Config Tested"),
                    ("auth_failed", "Authentication Failed"),
                    ("rate_limited", "Rate Limited"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
