# Generated by Django 5.2 on 2026-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageconfig",
            name="encrypt_at_rest",
            field=models.BooleanField(
                default=False,
                help_text="Encrypt stored files with AES-256-GCM before writing",
            ),
        ),
    ]
