# Generated by Django 5.2 on 2026-03-31 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_result_version_and_audit_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("job_created", "Job Created"),
                    ("job_completed", "Job Completed"),
                    ("job_failed", "Job Failed"),
                    ("job_updated", "Job Updated"),
                    ("job_reprocessed", "Job Reprocessed"),
                    ("result_accessed", "Result Accessed"),
                    ("result_deleted", "Result Deleted"),
                    ("data_deleted", "Data Deleted"),
                    ("data_auto_deleted", "Data Auto-Deleted"),
                    ("data_exported", "Data Exported"),
                    ("user_data_deleted", "User Data Deleted"),
                    ("storage_config_created", "Storage Config Created"),
                    ("storage_config_updated", "Storage Config Updated"),
                    ("storage_config_deleted", "Storage Config Deleted"),
                    ("storage_config_tested", "Storage Config Tested"),
                    ("auth_failed", "Authentication Failed"),
                    ("rate_limited", "Rate Limited"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
