# Generated by Django 5.2 on 2026-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rls_tenant_isolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="audio_storage_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key/path of the audio file in the storage backend",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="results_delivered",
            field=models.BooleanField(
                default=False,
                help_text="Whether results have been delivered to the client",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="results_delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When results were first delivered to the client",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("job_created", "Job Created"),
                    ("job_completed", "Job Completed"),
                    ("job_failed", "Job Failed"),
                    ("job_updated", "Job Updated"),
                    ("job_reprocessed", "Job Reprocessed"),
                    ("result_accessed", "Result Accessed"),
                    ("result_deleted", "Result Deleted"),
                    ("data_deleted", "Data Deleted"),
                    ("data_auto_deleted", "Data Auto-Deleted"),
                    ("data_exported", "Data Exported"),
                    ("user_data_deleted", "User Data Deleted"),
                    ("storage_config_created", "Storage Config Created"),
                    ("storage_config_updated", "Storage Config Updated"),
                    ("storage_config_deleted", "Storage Config Deleted"),
                    ("storage_config_tested", "Storage Config Tested"),
                    ("audio_deleted", "Audio Deleted"),
                    ("auth_failed", "Authentication Failed"),
                    ("rate_limited", "Rate Limited"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
