apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stt.fullname" . }}-config
  labels:
    {{- include "stt.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | default (randAlphaNum 50) | quote }}
  DATABASE_URL: "postgres://{{ .Values.database.user }}:$(POSTGRES_PASSWORD)@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
---
{{- if .Values.hfToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stt.fullname" . }}-ml-config
  labels:
    {{- include "stt.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_STT_TOKEN: {{ .Values.hfToken | quote }}
{{- end }}
